### ISSUE TITLE
Check if the socket is opened too soon

### ISSUE THREAD

**Issue by ricalo** [OfficeDev/Office-Add-in-Nodejs-ServerAuth#18]
The socket is opened when the main add-in page is loaded. For real-world scenarios that might be too soon.

**Comment by iambmelt** [comment]
No capacity for this enhancement currently. That said for RW scenarios, you're absolutely correct: socket should be opened on-demand and exist as ephemerally as possible.

Will leave this issue open for reference / future planning.

Thanks @Ricalo

**Comment by Rick-Kirkham** [comment]
Closing because the repo is being archived.
