### ISSUE TITLE
Browser warning message after auth has completed

### ISSUE THREAD

**Issue by dougperkes** [OfficeDev/Office-Add-in-Nodejs-ServerAuth#19]
The window.close() function causes the popped-up browser to issue a warning for the user to close the window once the auth flow has completed. We can avoid this by replacing `window.close()` with the following:

```javascript
window.open('', '_self', ''); window.close();
```

**Comment by Ricalo** [comment]
Thanks for the fix @dougperkes. I just tested and merged it.
